apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service # This is the name used in Nginx's proxy_pass
spec:
  selector:
    app: todo-backend
  ports:
    - protocol: TCP
      port: 8080 # Service port
      targetPort: 8080 # Container port
  type: ClusterIP # Internal service, not exposed directly to internet