apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
spec:
  selector:
    app: todo-frontend
  ports:
    - protocol: TCP
      port: 80 # Service port
      targetPort: 80 # Container port
  type: NodePort # Temporarily for testing, or use ClusterIP + Ingress